/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 BaseHeart.gltf 
Author: funnyeducomics (https://sketchfab.com/funnyeducomics)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cake-centered-original-color-b5970306c4bc4dca84c546b90ee7fe39
Title: Cake-centered-original Color
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BaseHeart(props) {
  const { nodes, materials } = useGLTF('/BaseHeart.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.blinn1SG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default BaseHeart;