/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Base2.gltf 
Author: funnyeducomics (https://sketchfab.com/funnyeducomics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/base-2-e29dfe07b5284a84be695db41b7bf258
Title: Base_2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Base2(props) {
  const { nodes, materials } = useGLTF('/Base2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.secondSG} scale={0.4}  rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default Base2;