/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Choco-heart.gltf 
Author: funnyeducomics (https://sketchfab.com/funnyeducomics)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/chocolate-heart-0ce93da4a08348ee9893edad07326390
Title: Chocolate-heart
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ChocoHeart(props) {
  const { nodes, materials } = useGLTF('/ChocoHeart.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.blinn1SG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default ChocoHeart;