/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Choco3.gltf 
Author: funnyeducomics (https://sketchfab.com/funnyeducomics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chocolate-3-77d4b23d00194909914ae48103805a17
Title: Chocolate_3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Choco3(props) {
  const { nodes, materials } = useGLTF('/Choco3.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Topping1SG} scale={0.4} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default Choco3;