/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Choco2.gltf 
Author: funnyeducomics (https://sketchfab.com/funnyeducomics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chocolate-2-ff1b78f367174359a7068f5a4d889852
Title: Chocolate 2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Choco2(props) {
  const { nodes, materials } = useGLTF('/Choco2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Topping1SG} scale={0.4} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default Choco2;