/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Strawberry.gltf 
Author: funnyeducomics (https://sketchfab.com/funnyeducomics)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cake-centered-strawberry-color-40ec80e59f0145309ccea2ce8a1088c5
Title: Cake-centered- Strawberry Color
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Strawberry(props) {
  const { nodes, materials } = useGLTF('/Strawberry.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.blinn1SG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default Strawberry;