/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Strawberry-heart.gltf 
Author: funnyeducomics (https://sketchfab.com/funnyeducomics)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/strawberry-heart-199f16f2b586450f9a560bdf7449a45a
Title: Strawberry-heart
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function StrawberryHeart(props) {
  const { nodes, materials } = useGLTF('/StrawberryHeart.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.pasted__pasted__blinn1SG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default StrawberryHeart;